version: '3'

services:
  comments_server:
    build: .
    ports:
      - 8080:8080
    environment:
      COMMENTO_ORIGIN: "${COMMENTO_ORIGIN}"
      COMMENTO_PORT: "${COMMENTO_PORT}"
      COMMENTO_POSTGRES: "${COMMENTO_POSTGRES}"
      COMMENTO_SMTP_HOST: "${COMMENTO_SMTP_HOST}"
      COMMENTO_SMTP_PORT: "${COMMENTO_SMTP_PORT}"
      COMMENTO_SMTP_USERNAME: "${COMMENTO_SMTP_USERNAME}"
      COMMENTO_SMTP_PASSWORD: "${COMMENTO_SMTP_PASSWORD}"
      COMMENTO_SMTP_FROM_ADDRESS: "${COMMENTO_SMTP_FROM_ADDRESS}"
      COMMENTO_GOOGLE_KEY: "${COMMENTO_GOOGLE_KEY}"
      COMMENTO_GOOGLE_SECRET: "${COMMENTO_GOOGLE_SECRET}"
      COMMENTO_GITHUB_KEY: "${COMMENTO_GITHUB_KEY}"
      COMMENTO_GITHUB_SECRET: "${COMMENTO_GITHUB_SECRET}"
      COMMENTO_IDP_ENDPOINT: "${COMMENTO_IDP_ENDPOINT}"
      COMMENTO_IDP_APIKEY: "${COMMENTO_IDP_APIKEY}"
    depends_on:
      - comments_db
    networks:
      - db_network
      
  comments_db:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - db_network
    volumes:
      - ./commentodb:/var/lib/postgresql/data

networks:
  db_network:
